### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getLastBufferRow' of undefined

### ISSUE THREAD

**Issue by ghost** [melke/markdown-folder#5]
[Enter steps to reproduce below:]
1. Packages menu -> Markdown Folder -> Fold All H2
2. Error, no folding.

**Atom Version**: 1.0.13
**System**: "Fedora release
**Thrown From**: [markdown-folder](https://github.com/melke/markdown-folder) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getLastBufferRow' of undefined

```
At /home/greyman/.atom/packages/markdown-folder/lib/markdown-folder.coffee:28

TypeError: Cannot read property 'getLastBufferRow' of undefined
  at Object.module.exports.MarkdownFolder.foldall (/home/greyman/.atom/packages/markdown-folder/lib/markdown-folder.coffee:28:23)
  at atom-workspace.subscriptions.add.atom.commands.add.markdown-folder:foldall-h2 (/home/greyman/.atom/packages/markdown-folder/lib/markdown-folder.coffee:14:94)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:240:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:145:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```
### Commands

```
     -0:57.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:57.4.0 core:delete (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:55.8.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:54.5.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:54.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:53.7.0 core:delete (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:52.2.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:50.8.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:50.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:49.7.0 core:delete (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:48.3.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:47.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:47.2.0 core:delete (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:46.1.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 87x -0:44.1.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:03.2.0 markdown-folder:foldall-h2 (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.12
atom-python-debugger, v0.3.4
auto-host-markdown-image, v0.2.4
markdown-folder, v0.3.0
markdown-lists, v0.0.2
markdown-preview-plus, v2.1.1
markdown-table-formatter, v2.5.3
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by melke** [comment]
Hi, thanks for reporting. Could you give me a sample markdown file where this is happening?

**Comment by melke** [comment]
Can you provide an example file for this? Otherwise, I will need to close this.
