### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by metasim** [melke/markdown-folder#6]
[Enter steps to reproduce below:]
1. Opened new markdown file
2. Right click, select "Toggle markdown-folder".

**Atom Version**: 1.0.15
**System**: Mac OS X 10.9.5
**Thrown From**: [markdown-folder](https://github.com/melke/markdown-folder) package, v0.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/sfitch/.atom/packages/markdown-folder/lib/markdown-folder.coffee:77

TypeError: Cannot read property 'match' of undefined
  at toggleFold (/Users/sfitch/.atom/packages/markdown-folder/lib/markdown-folder.coffee:77:51)
  at Object.module.exports.MarkdownFolder.folderer (/Users/sfitch/.atom/packages/markdown-folder/lib/markdown-folder.coffee:92:9)
  at Object.module.exports.MarkdownFolder.toggle (/Users/sfitch/.atom/packages/markdown-folder/lib/markdown-folder.coffee:24:6)
  at atom-workspace.subscriptions.add.atom.commands.add.markdown-folder:toggle (/Users/sfitch/.atom/packages/markdown-folder/lib/markdown-folder.coffee:12:90)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
  4x -1:33.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.6.0 atomic-emacs:forward-char (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:delete (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atomic-emacs, v0.7.3
markdown-folder, v0.3.0
markdown-preview-plus, v2.1.1

# Dev
No dev packages
```

**Comment by melke** [comment]
Thanks for reporting. Could you provide me with an example markdown file, that triggers this error?

**Comment by melke** [comment]
Also, could you please update to latest version, 0.3.1 and give me the updated stacktrace again?

**Comment by melke** [comment]
Can you provide an example file for this? Otherwise, I will need to close this.

**Comment by metasim** [comment]
Wasn't able to create a simplified example.
